// AUTO-GENERATED by scripts/generate-i18n.mjs — do not edit by hand
import type { Locale } from './types'

export interface LabelMaps {
  artifactType: Record<string, string>
  stage: Record<string, string>
  strategy: Record<string, string>
  outcome: Record<string, string>
  scenario: Record<string, string>
  mode: Record<string, string>
  plan: Record<string, string>
  variableNames: Record<string, string>
  scoreGroups: { key: string; label: string; subtitle: string }[]
}

const DATA: Record<Locale, LabelMaps> = {
  "zh-CN": {
    "artifactType": {
      "software": "软件",
      "app": "App",
      "game": "游戏",
      "website": "网站",
      "video": "视频",
      "article": "文章",
      "community": "社区",
      "ai_agent": "AI Agent",
      "business_idea": "商业创意",
      "open_source": "开源项目"
    },
    "stage": {
      "idea": "想法",
      "prototype": "原型",
      "demo": "Demo",
      "mvp": "MVP",
      "launched": "已发布",
      "growth": "增长期",
      "stagnant": "停滞期",
      "decline": "衰退期"
    },
    "strategy": {
      "original": "原始版本",
      "clarity_boost": "强化清晰度",
      "distribution_boost": "强化传播性",
      "retention_boost": "强化留存",
      "monetization_boost": "强化商业化",
      "quality_boost": "强化质量稳定性",
      "community_boost": "强化社区"
    },
    "outcome": {
      "dead": "死亡 / 无效发布",
      "low_alive": "低热度存活",
      "niche_success": "小众成功",
      "moderate_success": "中等成功",
      "clear_success": "明显成功",
      "blockbuster": "爆款 / 头部",
      "long_compound": "长期复利型"
    },
    "scenario": {
      "baseline": "基准场景",
      "optimistic": "乐观场景",
      "pessimistic": "悲观场景",
      "black_swan": "黑天鹅场景",
      "long_compound": "长期复利场景",
      "competitor_shock": "竞品冲击",
      "platform_boost": "平台推荐",
      "negative_event": "负面事件"
    },
    "mode": {
      "quick": "快速模式 (1万次)",
      "standard": "标准模式 (5万次)",
      "deep": "深度模式 (10万次)",
      "ultra": "机构级 (50万次)"
    },
    "plan": {
      "free": "免费版",
      "pro": "Pro 会员",
      "team": "Team"
    },
    "variableNames": {
      "quality": "质量",
      "originality": "新颖度",
      "clarity": "清晰度",
      "usability": "易用性",
      "emotionalHook": "情绪钩子",
      "differentiation": "差异化",
      "completeness": "完成度",
      "reliability": "稳定性",
      "aestheticQuality": "审美质量",
      "problemSolutionFit": "问题匹配度",
      "marketSize": "市场空间",
      "audiencePain": "痛点强度",
      "willingnessToPay": "付费意愿",
      "trendFit": "趋势匹配",
      "timingScore": "时机成熟度",
      "competitionIntensity": "竞争强度",
      "substitutionRisk": "替代风险",
      "platformDependency": "平台依赖",
      "regulatoryRisk": "政策风险",
      "categoryGrowth": "品类增长",
      "shareability": "可分享性",
      "viralityPotential": "病毒传播",
      "storyValue": "故事性",
      "socialProofPotential": "社会证明",
      "creatorReputation": "创作者影响力",
      "distributionPower": "渠道能力",
      "communityPotential": "社区潜力",
      "mediaFriendliness": "媒体友好",
      "recommendationFit": "推荐适配",
      "visualSpreadPower": "视觉传播力",
      "activationRatePotential": "激活潜力",
      "firstSessionValue": "首次体验",
      "retentionPotential": "留存潜力",
      "habitPotential": "习惯形成",
      "networkEffect": "网络效应",
      "switchingCost": "迁移成本",
      "longTermValue": "长期价值",
      "updateVelocity": "迭代能力",
      "feedbackLoopStrength": "反馈闭环",
      "communityLockIn": "社区锁定",
      "monetizationFit": "变现适配",
      "pricingPower": "定价能力",
      "arpuPotential": "单用户价值",
      "conversionPotential": "转化潜力",
      "upsellPotential": "增购潜力",
      "enterprisePotential": "企业潜力",
      "lowCostDistribution": "低成本获客",
      "grossMarginPotential": "毛利潜力",
      "lifecycleValue": "生命周期价值",
      "revenueDiversity": "收入多样性",
      "executionRisk": "执行风险",
      "technicalDebt": "技术债",
      "churnRisk": "流失风险",
      "negativeFeedbackRisk": "负面反馈风险",
      "copycatRisk": "被复制风险",
      "scalabilityRisk": "扩展风险",
      "maintenanceBurden": "维护负担",
      "legalRisk": "法律风险",
      "platformBanRisk": "平台封禁风险",
      "founderDependency": "创始人依赖"
    },
    "scoreGroups": [
      {
        "key": "artifact",
        "label": "作品本体",
        "subtitle": "你的作品本身的质量和特征"
      },
      {
        "key": "market",
        "label": "市场环境",
        "subtitle": "市场空间、竞争和时机"
      },
      {
        "key": "distribution",
        "label": "传播能力",
        "subtitle": "作品的传播和扩散潜力"
      },
      {
        "key": "retention",
        "label": "留存能力",
        "subtitle": "用户留存和长期价值"
      },
      {
        "key": "business",
        "label": "商业化能力",
        "subtitle": "变现和商业潜力"
      },
      {
        "key": "risk",
        "label": "风险因子",
        "subtitle": "可能拖累作品的负面因素（分数越高风险越大）"
      }
    ]
  },
  "en-US": {
    "artifactType": {
      "software": "Software",
      "app": "App",
      "game": "Game",
      "website": "Website",
      "video": "Video",
      "article": "Article",
      "community": "Community",
      "ai_agent": "AI Agent",
      "business_idea": "Business idea",
      "open_source": "Open source"
    },
    "stage": {
      "idea": "Idea",
      "prototype": "Prototype",
      "demo": "Demo",
      "mvp": "MVP",
      "launched": "Launched",
      "growth": "Growth",
      "stagnant": "Stagnant",
      "decline": "Decline"
    },
    "strategy": {
      "original": "Baseline",
      "clarity_boost": "Clarity boost",
      "distribution_boost": "Distribution boost",
      "retention_boost": "Retention boost",
      "monetization_boost": "Monetization boost",
      "quality_boost": "Quality boost",
      "community_boost": "Community boost"
    },
    "outcome": {
      "dead": "Dead / failed launch",
      "low_alive": "Low traction",
      "niche_success": "Niche success",
      "moderate_success": "Moderate success",
      "clear_success": "Clear success",
      "blockbuster": "Blockbuster",
      "long_compound": "Long-term compound"
    },
    "scenario": {
      "baseline": "Baseline",
      "optimistic": "Optimistic",
      "pessimistic": "Pessimistic",
      "black_swan": "Black swan",
      "long_compound": "Long compound",
      "competitor_shock": "Competitor shock",
      "platform_boost": "Platform boost",
      "negative_event": "Negative event"
    },
    "mode": {
      "quick": "Quick (10K runs)",
      "standard": "Standard (50K runs)",
      "deep": "Deep (100K runs)",
      "ultra": "Institutional (500K runs)"
    },
    "plan": {
      "free": "Free",
      "pro": "Pro",
      "team": "Team"
    },
    "variableNames": {
      "quality": "Quality",
      "originality": "Originality",
      "clarity": "Clarity",
      "usability": "Usability",
      "emotionalHook": "Emotional hook",
      "differentiation": "Differentiation",
      "completeness": "Completeness",
      "reliability": "Reliability",
      "aestheticQuality": "Aesthetics",
      "problemSolutionFit": "Problem-solution fit",
      "marketSize": "Market size",
      "audiencePain": "Audience pain",
      "willingnessToPay": "Willingness to pay",
      "trendFit": "Trend fit",
      "timingScore": "Timing",
      "competitionIntensity": "Competition",
      "substitutionRisk": "Substitution risk",
      "platformDependency": "Platform dependency",
      "regulatoryRisk": "Regulatory risk",
      "categoryGrowth": "Category growth",
      "shareability": "Shareability",
      "viralityPotential": "Virality",
      "storyValue": "Story value",
      "socialProofPotential": "Social proof",
      "creatorReputation": "Creator reputation",
      "distributionPower": "Distribution",
      "communityPotential": "Community potential",
      "mediaFriendliness": "Media friendly",
      "recommendationFit": "Recommendation fit",
      "visualSpreadPower": "Visual spread",
      "activationRatePotential": "Activation",
      "firstSessionValue": "First session value",
      "retentionPotential": "Retention",
      "habitPotential": "Habit potential",
      "networkEffect": "Network effect",
      "switchingCost": "Switching cost",
      "longTermValue": "Long-term value",
      "updateVelocity": "Update velocity",
      "feedbackLoopStrength": "Feedback loop",
      "communityLockIn": "Community lock-in",
      "monetizationFit": "Monetization fit",
      "pricingPower": "Pricing power",
      "arpuPotential": "ARPU potential",
      "conversionPotential": "Conversion",
      "upsellPotential": "Upsell",
      "enterprisePotential": "Enterprise",
      "lowCostDistribution": "Low-cost acquisition",
      "grossMarginPotential": "Gross margin",
      "lifecycleValue": "Lifecycle value",
      "revenueDiversity": "Revenue diversity",
      "executionRisk": "Execution risk",
      "technicalDebt": "Technical debt",
      "churnRisk": "Churn risk",
      "negativeFeedbackRisk": "Negative feedback",
      "copycatRisk": "Copycat risk",
      "scalabilityRisk": "Scalability risk",
      "maintenanceBurden": "Maintenance burden",
      "legalRisk": "Legal risk",
      "platformBanRisk": "Platform ban risk",
      "founderDependency": "Founder dependency"
    },
    "scoreGroups": [
      {
        "key": "artifact",
        "label": "Product",
        "subtitle": "Quality and traits of your product"
      },
      {
        "key": "market",
        "label": "Market",
        "subtitle": "Space, competition, and timing"
      },
      {
        "key": "distribution",
        "label": "Distribution",
        "subtitle": "Spread and reach potential"
      },
      {
        "key": "retention",
        "label": "Retention",
        "subtitle": "User retention and long-term value"
      },
      {
        "key": "business",
        "label": "Monetization",
        "subtitle": "Revenue and business potential"
      },
      {
        "key": "risk",
        "label": "Risk factors",
        "subtitle": "Negative factors (higher = more risk)"
      }
    ]
  },
  "ja-JP": {
    "artifactType": {
      "software": "ソフトウェア",
      "app": "アプリ",
      "game": "ゲーム",
      "website": "ウェブサイト",
      "video": "動画",
      "article": "記事",
      "community": "コミュニティ",
      "ai_agent": "AIエージェント",
      "business_idea": "ビジネスアイデア",
      "open_source": "オープンソース"
    },
    "stage": {
      "idea": "アイデア",
      "prototype": "プロトタイプ",
      "demo": "デモ",
      "mvp": "MVP",
      "launched": "リリース済み",
      "growth": "成長期",
      "stagnant": "停滞期",
      "decline": "衰退期"
    },
    "strategy": {
      "original": "現状維持",
      "clarity_boost": "明確さ強化",
      "distribution_boost": "拡散強化",
      "retention_boost": "リテンション強化",
      "monetization_boost": "収益化強化",
      "quality_boost": "品質強化",
      "community_boost": "コミュニティ強化"
    },
    "outcome": {
      "dead": "死亡 / 失敗リリース",
      "low_alive": "低熱量存続",
      "niche_success": "ニッチ成功",
      "moderate_success": "中程度の成功",
      "clear_success": "明確な成功",
      "blockbuster": "ヒット / トップ",
      "long_compound": "長期複利型"
    },
    "scenario": {
      "baseline": "ベースライン",
      "optimistic": "楽観",
      "pessimistic": "悲観",
      "black_swan": "ブラックスワン",
      "long_compound": "長期複利",
      "competitor_shock": "競合ショック",
      "platform_boost": "プラットフォーム推薦",
      "negative_event": "ネガティブイベント"
    },
    "mode": {
      "quick": "クイック (1万回)",
      "standard": "標準 (5万回)",
      "deep": "ディープ (10万回)",
      "ultra": "機関向け (50万回)"
    },
    "plan": {
      "free": "無料",
      "pro": "Pro",
      "team": "Team"
    },
    "variableNames": {
      "quality": "品質",
      "originality": "新規性",
      "clarity": "明確さ",
      "usability": "使いやすさ",
      "emotionalHook": "感情フック",
      "differentiation": "差別化",
      "completeness": "完成度",
      "reliability": "安定性",
      "aestheticQuality": "美的品質",
      "problemSolutionFit": "課題適合",
      "marketSize": "市場規模",
      "audiencePain": "ペイン強度",
      "willingnessToPay": "支払意欲",
      "trendFit": "トレンド適合",
      "timingScore": "タイミング",
      "competitionIntensity": "競争強度",
      "substitutionRisk": "代替リスク",
      "platformDependency": "プラットフォーム依存",
      "regulatoryRisk": "規制リスク",
      "categoryGrowth": "カテゴリ成長",
      "shareability": "共有可能性",
      "viralityPotential": "バイラル性",
      "storyValue": "ストーリー性",
      "socialProofPotential": "社会的証明",
      "creatorReputation": "クリエイター影響力",
      "distributionPower": "配信力",
      "communityPotential": "コミュニティ潜在力",
      "mediaFriendliness": "メディア適性",
      "recommendationFit": "推薦適合",
      "visualSpreadPower": "視覚拡散力",
      "activationRatePotential": "活性化潜在力",
      "firstSessionValue": "初回体験",
      "retentionPotential": "リテンション",
      "habitPotential": "習慣形成",
      "networkEffect": "ネットワーク効果",
      "switchingCost": "乗り換えコスト",
      "longTermValue": "長期価値",
      "updateVelocity": "更新速度",
      "feedbackLoopStrength": "フィードバックループ",
      "communityLockIn": "コミュニティロックイン",
      "monetizationFit": "収益化適合",
      "pricingPower": "価格決定力",
      "arpuPotential": "ARPU潜在力",
      "conversionPotential": "コンバージョン",
      "upsellPotential": "アップセル",
      "enterprisePotential": "エンタープライズ",
      "lowCostDistribution": "低コスト獲得",
      "grossMarginPotential": "粗利潜在力",
      "lifecycleValue": "LTV",
      "revenueDiversity": "収益多様性",
      "executionRisk": "実行リスク",
      "technicalDebt": "技術的負債",
      "churnRisk": "解約リスク",
      "negativeFeedbackRisk": "ネガティブフィードバック",
      "copycatRisk": "模倣リスク",
      "scalabilityRisk": "拡張リスク",
      "maintenanceBurden": "保守負担",
      "legalRisk": "法的リスク",
      "platformBanRisk": "BANリスク",
      "founderDependency": "創業者依存"
    },
    "scoreGroups": [
      {
        "key": "artifact",
        "label": "プロダクト本体",
        "subtitle": "作品の品質と特徴"
      },
      {
        "key": "market",
        "label": "市場環境",
        "subtitle": "市場規模・競合・タイミング"
      },
      {
        "key": "distribution",
        "label": "拡散力",
        "subtitle": "拡散・リーチの潜在力"
      },
      {
        "key": "retention",
        "label": "リテンション",
        "subtitle": "継続利用と長期価値"
      },
      {
        "key": "business",
        "label": "収益化",
        "subtitle": "マネタイズとビジネス潜在力"
      },
      {
        "key": "risk",
        "label": "リスク要因",
        "subtitle": "ネガティブ要因（高いほどリスク大）"
      }
    ]
  },
  "ko-KR": {
    "artifactType": {
      "software": "소프트웨어",
      "app": "앱",
      "game": "게임",
      "website": "웹사이트",
      "video": "영상",
      "article": "글",
      "community": "커뮤니티",
      "ai_agent": "AI 에이전트",
      "business_idea": "비즈니스 아이디어",
      "open_source": "오픈소스"
    },
    "stage": {
      "idea": "아이디어",
      "prototype": "프로토타입",
      "demo": "데모",
      "mvp": "MVP",
      "launched": "출시됨",
      "growth": "성장기",
      "stagnant": "정체기",
      "decline": "쇠퇴기"
    },
    "strategy": {
      "original": "기본 버전",
      "clarity_boost": "명확성 강화",
      "distribution_boost": "유통 강화",
      "retention_boost": "리텐션 강화",
      "monetization_boost": "수익화 강화",
      "quality_boost": "품질 강화",
      "community_boost": "커뮤니티 강화"
    },
    "outcome": {
      "dead": "실패 / 무효 출시",
      "low_alive": "저조한 생존",
      "niche_success": "니치 성공",
      "moderate_success": "중간 성공",
      "clear_success": "뚜렷한 성공",
      "blockbuster": "대히트 / 상위",
      "long_compound": "장기 복리형"
    },
    "scenario": {
      "baseline": "기준 시나리오",
      "optimistic": "낙관",
      "pessimistic": "비관",
      "black_swan": "블랙스완",
      "long_compound": "장기 복리",
      "competitor_shock": "경쟁 충격",
      "platform_boost": "플랫폼 부스트",
      "negative_event": "부정 이벤트"
    },
    "mode": {
      "quick": "빠른 (1만 회)",
      "standard": "표준 (5만 회)",
      "deep": "심층 (10만 회)",
      "ultra": "기관 (50만 회)"
    },
    "plan": {
      "free": "무료",
      "pro": "Pro",
      "team": "Team"
    },
    "variableNames": {
      "quality": "품질",
      "originality": "독창성",
      "clarity": "명확성",
      "usability": "사용성",
      "emotionalHook": "감정 훅",
      "differentiation": "차별화",
      "completeness": "완성도",
      "reliability": "안정성",
      "aestheticQuality": "미적 품질",
      "problemSolutionFit": "문제 적합도",
      "marketSize": "시장 규모",
      "audiencePain": "페인 강도",
      "willingnessToPay": "지불 의향",
      "trendFit": "트렌드 적합",
      "timingScore": "타이밍",
      "competitionIntensity": "경쟁 강도",
      "substitutionRisk": "대체 위험",
      "platformDependency": "플랫폼 의존",
      "regulatoryRisk": "규제 위험",
      "categoryGrowth": "카테고리 성장",
      "shareability": "공유성",
      "viralityPotential": "바이럴",
      "storyValue": "스토리 가치",
      "socialProofPotential": "사회적 증거",
      "creatorReputation": "크리에이터 영향력",
      "distributionPower": "유통력",
      "communityPotential": "커뮤니티 잠재력",
      "mediaFriendliness": "미디어 친화",
      "recommendationFit": "추천 적합",
      "visualSpreadPower": "시각 확산력",
      "activationRatePotential": "활성화 잠재력",
      "firstSessionValue": "첫 세션 가치",
      "retentionPotential": "리텐션",
      "habitPotential": "습관 형성",
      "networkEffect": "네트워크 효과",
      "switchingCost": "전환 비용",
      "longTermValue": "장기 가치",
      "updateVelocity": "업데이트 속도",
      "feedbackLoopStrength": "피드백 루프",
      "communityLockIn": "커뮤니티 락인",
      "monetizationFit": "수익화 적합",
      "pricingPower": "가격 결정력",
      "arpuPotential": "ARPU 잠재력",
      "conversionPotential": "전환 잠재력",
      "upsellPotential": "업셀",
      "enterprisePotential": "엔터프라이즈",
      "lowCostDistribution": "저비용 획득",
      "grossMarginPotential": "총마진",
      "lifecycleValue": "생애 가치",
      "revenueDiversity": "수익 다양성",
      "executionRisk": "실행 위험",
      "technicalDebt": "기술 부채",
      "churnRisk": "이탈 위험",
      "negativeFeedbackRisk": "부정 피드백",
      "copycatRisk": "모방 위험",
      "scalabilityRisk": "확장 위험",
      "maintenanceBurden": "유지 부담",
      "legalRisk": "법적 위험",
      "platformBanRisk": "플랫폼 제재",
      "founderDependency": "창업자 의존"
    },
    "scoreGroups": [
      {
        "key": "artifact",
        "label": "제품 본체",
        "subtitle": "작품의 품질과 특성"
      },
      {
        "key": "market",
        "label": "시장 환경",
        "subtitle": "시장 규모, 경쟁, 타이밍"
      },
      {
        "key": "distribution",
        "label": "확산력",
        "subtitle": "확산 및 도달 잠재력"
      },
      {
        "key": "retention",
        "label": "리텐션",
        "subtitle": "사용자 유지와 장기 가치"
      },
      {
        "key": "business",
        "label": "수익화",
        "subtitle": "수익 및 비즈니스 잠재력"
      },
      {
        "key": "risk",
        "label": "리스크 요인",
        "subtitle": "부정 요인 (높을수록 위험)"
      }
    ]
  }
}

export function getLabels(locale: Locale): LabelMaps {
  return DATA[locale] ?? DATA['zh-CN']
}
